In [47]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix


In [3]:
dataset = pd.read_csv(r"C:\Users\88001381\Desktop\PV_Model_Data.csv")

In [4]:
print(dataset.shape)

(135020, 70)


In [11]:
X_train = dataset.iloc[:, :-1]  
y_train = dataset.iloc[:, -1]    


In [42]:
y_train

0         3
1         3
2         0
3         3
4         3
         ..
135015    3
135016    3
135017    0
135018    0
135019    3
Name: Restructuring_Flag_B, Length: 135020, dtype: int64

In [27]:
rf_classifier = RandomForestClassifier(n_estimators=100, criterion = 'entropy', random_state=0, max_depth = 100)

In [28]:
rf_classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', max_depth=100, random_state=0)

In [29]:
y_pred = rf_classifier.predict(X_train)

In [30]:
conf_matrix = confusion_matrix(y_train, y_pred)
print(conf_matrix)


[[ 19500      0      0      0]
 [     0   8652      0      0]
 [     0      0    807      0]
 [     0      0      0 106061]]


In [62]:
dataset1 = pd.read_csv(r"C:\Users\88001381\Desktop\PV_Model_Data(1).csv")

In [63]:
dataset2 = pd.read_excel(r"C:\Users\88001381\Desktop\PV_Model_Data(2).xlsx")

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\88001381\\Desktop\\PV_Model_Data(2).xlsx'

In [60]:
train = pd.read_excel(r"C:/Users/88001381/Desktop/train.xlsx")

KeyboardInterrupt: 

In [61]:
print(dataset1.shape)


(135020, 69)


In [35]:
X_train1 = dataset1.iloc[:, :-1]  
y_train1 = dataset1.iloc[:, -1]  

In [36]:
rf_classifier = RandomForestClassifier(n_estimators=100, criterion = 'entropy', random_state=0, max_depth = 100)

In [38]:
rf_classifier.fit(X_train1, y_train1)

RandomForestClassifier(criterion='entropy', max_depth=100, random_state=0)

In [39]:
y_pred1 = rf_classifier.predict(X_train1)

In [40]:
conf_matrix1 = confusion_matrix(y_train1, y_pred1)
print(conf_matrix1)

[[ 19500      0      0      0]
 [     0   8652      0      0]
 [     0      0    807      0]
 [     0      0      0 106061]]


In [41]:
y_train1    

0         3
1         3
2         0
3         3
4         3
         ..
135015    3
135016    3
135017    0
135018    0
135019    3
Name: Restructuring_Flag_B, Length: 135020, dtype: int64