In [4]:
dataset = pd.read_csv(r"C:\Users\88001381\Desktop\PV_Model_Data.csv")

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [6]:
dataset["EMI1"].isnull().sum()

2812

In [10]:
dataset["EMI1"].count()

132243

In [8]:
dataset.isnull().sum()

Month                   0
FIN_AMOUNT              0
IRR_CUSTOMER            0
REGION_NEW              0
ASSET_COST              0
                       ..
PDC_FLAG_B              0
SCHEME_FINPROD_B        0
TRACK_RECORD_B          0
REGION_NEW_B            0
Restructuring_Flag_B    0
Length: 81, dtype: int64

In [42]:
X = dataset.iloc[:, :-1]
y = dataset.iloc[:, -1]

In [43]:
print(dataset.shape)

(135020, 70)


In [44]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30, random_state = 0)
print(X_train)
print(y_train)
print(X_test)
print(y_test)


         Month  FIN_AMOUNT  IRR_CUSTOMER  ASSET_COST       LTV  \
20479   202207    777043.0        10.476    853278.0  0.910656   
38732   202201     81946.0        13.941    125400.0  0.653477   
132754  202202    600000.0         9.998    927663.0  0.646787   
20279   202111     66481.0        13.945    101894.0  0.652453   
39667   202205    119500.0        13.998    119500.0  1.000000   
...        ...         ...           ...         ...       ...   
41993   202205    549000.0        10.022    578670.0  0.948727   
97639   202112   1416000.0        10.527   2115723.0  0.669275   
95939   202205    551444.0        12.059   1199463.0  0.449445   
117952  202201    400000.0        11.598    540226.0  0.740431   
43567   202112    374439.0         9.989    464056.0  0.799990   

        COLLECTION_TILL_DATE         SOHP  TENURE  ODAMT  COLLECTION_MONTH  \
20479               222700.0   662330.560      84    0.0           13100.0   
38732                 2868.0    81829.420      12  

In [45]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
print(X_train)

[[ 0.81406955  0.4671853  -0.46268324 ...  0.42227466 -0.39364999
   1.96856837]
 [ 0.68124133 -0.85657798  1.40329276 ...  1.57451357 -0.39364999
  -0.66531146]
 [ 0.70337937  0.13001938 -0.72009638 ... -0.72996425 -0.39364999
  -0.66531146]
 ...
 [ 0.76979348  0.03754789  0.38979584 ... -0.72996425 -0.39364999
  -0.66531146]
 [ 0.68124133 -0.25086654  0.14153756 ... -0.72996425  0.99383593
   0.65162846]
 [-1.28904398 -0.29954566 -0.72494307 ... -0.72996425  0.99383593
  -0.66531146]]


In [20]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print(X_train)
print(X_test)


ValueError: Input contains infinity or a value too large for dtype('float64').

In [61]:
y_train.shape

(94514,)

In [46]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 100, criterion = 'entropy', random_state = 0, max_depth = 100)


In [47]:
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', max_depth=100, random_state=0)

In [67]:
y_pred = classifier.predict(X_train)

In [68]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_train, y_pred)
print(cm)
print(accuracy_score(y_train, y_pred))

[[13596     0     0     0]
 [    0  6085     0     0]
 [    0     0   555     0]
 [    0     0     0 74278]]
1.0


In [69]:
cm = confusion_matrix(y_train, y_pred)
print(cm)

[[13596     0     0     0]
 [    0  6085     0     0]
 [    0     0   555     0]
 [    0     0     0 74278]]


In [70]:
y_pred

array([3, 0, 3, ..., 3, 3, 3], dtype=int64)

In [71]:
y_train

20479     3
38732     0
132754    3
20279     0
39667     0
         ..
41993     3
97639     3
95939     3
117952    3
43567     3
Name: Restructuring_Flag_B, Length: 94514, dtype: int64

In [73]:

y_pred.value_counts()


AttributeError: 'numpy.ndarray' object has no attribute 'value_counts'

In [30]:
print(dataset.isnull().sum())

Month                   0
FIN_AMOUNT              0
IRR_CUSTOMER            0
REGION_NEW              0
ASSET_COST              0
                       ..
PDC_FLAG_B              0
SCHEME_FINPROD_B        0
TRACK_RECORD_B          0
REGION_NEW_B            0
Restructuring_Flag_B    0
Length: 81, dtype: int64


In [28]:
np.isnan(mat.any()) #and gets False
np.isfinite(mat.all()) #and gets True

NameError: name 'mat' is not defined

In [26]:
import pandas as pd
import numpy as np

def clean_dataset(df):
    assert isinstance(df, pd.DataFrame)
    df.dropna(inplace=True)
    indices_to_keep = ~df.isin([np.nan, np.inf, -np.inf]).any(axis=1)
    return df[indices_to_keep].astype(np.float64)

In [29]:
mat[np.isfinite(mat) == True] = 0

NameError: name 'mat' is not defined

In [31]:
dataset.isnull()

Month  FIN_AMOUNT  IRR_CUSTOMER  REGION_NEW  ASSET_COST    LTV  \
0       False       False         False       False       False  False   
1       False       False         False       False       False  False   
2       False       False         False       False       False  False   
3       False       False         False       False       False  False   
4       False       False         False       False       False  False   
...       ...         ...           ...         ...         ...    ...   
135050  False       False         False       False       False  False   
135051  False       False         False       False       False  False   
135052  False       False         False       False       False  False   
135053  False       False         False       False       False  False   
135054  False       False         False       False       False  False   

        COMPANY_CODE  COLLECTION_TILL_DATE   SOHP  TENURE  ...  \
0              False                 False  False   False  ...   
1              False                 False  False   False  ...   
2              False                 False  False   False  ...   
3              False                 False  False   False  ...   
4              False                 False  False   False  ...   
...              ...                   ...    ...     ...  ...   
135050         False                 False  False   False  ...   
135051         False                 False  False   False  ...   
135052         False                 False  False   False  ...   
135053         False                 False  False   False  ...   
135054         False                 False  False   False  ...   

        ASSET_CATEGORY2_B  NORM_B  CUSTOMER_SEGMENT_B  COMPANY_INDIVIDUAL_B  \
0                   False   False               False                 False   
1                   False   False               False                 False   
2                   False   False               False                 False   
3                   False   False               False                 False   
4                   False   False               False                 False   
...                   ...     ...                 ...                   ...   
135050              False   False               False                 False   
135051              False   False               False                 False   
135052              False   False               False                 False   
135053              False   False               False                 False   
135054              False   False               False                 False   

        SOURCING_B  PDC_FLAG_B  SCHEME_FINPROD_B  TRACK_RECORD_B  \
0            False       False             False           False   
1            False       False             False           False   
2            False       False             False           False   
3            False       False             False           False   
4            False       False             False           False   
...            ...         ...               ...             ...   
135050       False       False             False           False   
135051       False       False             False           False   
135052       False       False             False           False   
135053       False       False             False           False   
135054       False       False             False           False   

        REGION_NEW_B  Restructuring_Flag_B  
0              False                 False  
1              False                 False  
2              False                 False  
3              False                 False  
4              False                 False  
...              ...                   ...  
135050         False                 False  
135051         False                 False  
135052         False                 False  
135053         False                 False  
135054         False                 False  

[135055 rows x 81 c

In [33]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    print(dataset.isnull().sum())


Month                       0
FIN_AMOUNT                  0
IRR_CUSTOMER                0
REGION_NEW                  0
ASSET_COST                  0
LTV                         0
COMPANY_CODE                0
COLLECTION_TILL_DATE        0
SOHP                        0
TENURE                      0
ODAMT                       0
COLLECTION_MONTH            0
FIRST_EMI                   0
EMI                         0
ODBKT                       0
INCEPTION_MONTH             0
MOB                         0
SOHPOD                      0
SOHPOD_PREASSIGN            0
SOHPOD_MOB1PLUS          5751
SOHPOD_MOB2PLUS          8696
SOHPOD_MOB3PLUS         11669
SOHPOD_MOB4PLUS         14626
SOHPOD_MOB5PLUS         18106
SOHPOD_MOB6PLUS         21641
PAID_PER                    0
TENURE_LEFT                 0
ME                       2796
CE                       2799
max_odbkt                   0
Ever_30                     0
Ever_60                     0
Ever_90                     0
max_dpd   

In [34]:
dataset = pd.read_csv(r"C:\Users\88001381\Desktop\PV_Model_Data.csv")

In [35]:
print(dataset.shape)

(135055, 70)


In [36]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 135055 entries, 0 to 135054
Data columns (total 70 columns):
 #   Column                Non-Null Count   Dtype  
---  ------                --------------   -----  
 0   Month                 135055 non-null  int64  
 1   FIN_AMOUNT            135055 non-null  float64
 2   IRR_CUSTOMER          135055 non-null  float64
 3   ASSET_COST            135055 non-null  float64
 4   LTV                   135055 non-null  float64
 5   COLLECTION_TILL_DATE  135055 non-null  float64
 6   SOHP                  135055 non-null  float64
 7   TENURE                135055 non-null  int64  
 8   ODAMT                 135055 non-null  float64
 9   COLLECTION_MONTH      135055 non-null  float64
 10  FIRST_EMI             135055 non-null  int64  
 11  EMI                   135055 non-null  float64
 12  ODBKT                 135055 non-null  int64  
 13  INCEPTION_MONTH       135055 non-null  int64  
 14  MOB                   135055 non-null  int64  
 15  

In [37]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    print(dataset.isnull().sum())


Month                    0
FIN_AMOUNT               0
IRR_CUSTOMER             0
ASSET_COST               0
LTV                      0
COLLECTION_TILL_DATE     0
SOHP                     0
TENURE                   0
ODAMT                    0
COLLECTION_MONTH         0
FIRST_EMI                0
EMI                      0
ODBKT                    0
INCEPTION_MONTH          0
MOB                      0
SOHPOD                   0
SOHPOD_PREASSIGN         0
PAID_PER                 0
TENURE_LEFT              0
max_odbkt                0
Ever_30                  0
Ever_60                  0
Ever_90                  0
max_dpd                  0
target_variable          0
EverInBkt_1_3M           0
EverInBkt_2_3M           0
EverInBkt_3_3M           0
EverInBkt_4Plus_3M       0
EverInBkt_1_6M           0
EverInBkt_2_6M           0
EverInBkt_3_6M           0
EverInBkt_4Plus_6M       0
EverInBkt_1_9M           0
EverInBkt_2_9M           0
EverInBkt_3_9M           0
EverInBkt_4Plus_9M       0
E

In [38]:
dataset = pd.read_csv(r"C:\Users\88001381\Desktop\PV_Model_Data.csv")

In [40]:
print(dataset.shape)

(135020, 70)


In [41]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    print(dataset.isnull().sum())

Month                   0
FIN_AMOUNT              0
IRR_CUSTOMER            0
ASSET_COST              0
LTV                     0
COLLECTION_TILL_DATE    0
SOHP                    0
TENURE                  0
ODAMT                   0
COLLECTION_MONTH        0
FIRST_EMI               0
EMI                     0
ODBKT                   0
INCEPTION_MONTH         0
MOB                     0
SOHPOD                  0
SOHPOD_PREASSIGN        0
PAID_PER                0
TENURE_LEFT             0
max_odbkt               0
Ever_30                 0
Ever_60                 0
Ever_90                 0
max_dpd                 0
target_variable         0
EverInBkt_1_3M          0
EverInBkt_2_3M          0
EverInBkt_3_3M          0
EverInBkt_4Plus_3M      0
EverInBkt_1_6M          0
EverInBkt_2_6M          0
EverInBkt_3_6M          0
EverInBkt_4Plus_6M      0
EverInBkt_1_9M          0
EverInBkt_2_9M          0
EverInBkt_3_9M          0
EverInBkt_4Plus_9M      0
EverInBkt_1_12M         0
EverInBkt_2_

In [74]:
X_train

array([[ 0.81406955,  0.4671853 , -0.46268324, ...,  0.42227466,
        -0.39364999,  1.96856837],
       [ 0.68124133, -0.85657798,  1.40329276, ...,  1.57451357,
        -0.39364999, -0.66531146],
       [ 0.70337937,  0.13001938, -0.72009638, ..., -0.72996425,
        -0.39364999, -0.66531146],
       ...,
       [ 0.76979348,  0.03754789,  0.38979584, ..., -0.72996425,
        -0.39364999, -0.66531146],
       [ 0.68124133, -0.25086654,  0.14153756, ..., -0.72996425,
         0.99383593,  0.65162846],
       [-1.28904398, -0.29954566, -0.72494307, ..., -0.72996425,
         0.99383593, -0.66531146]])

In [79]:
X_train.tolist()

[[0.8140695530158418,
  0.4671853006204171,
  -0.4626832386743944,
  0.29212100455164774,
  0.6860943521361296,
  -0.19100068750025656,
  0.9784644649388325,
  1.1047353585771316,
  -0.060793459593752694,
  0.07489216212386651,
  1.0447283525427056,
  0.08910956973523251,
  -0.08033022407620344,
  1.0836301217819981,
  -0.45494985715108516,
  0.9768837033926152,
  0.8456408894650829,
  -0.7180644846438187,
  1.5814385724812892,
  -0.3386619597010102,
  -0.2864040326483351,
  -0.22494253012691132,
  -0.1254331560053807,
  -0.5875582982531088,
  -0.32186026621208585,
  -0.2638769236391615,
  -0.2637779647194653,
  -0.2637669901373215,
  -0.26374003620523007,
  -0.3944999659336615,
  -0.39437477630702794,
  -0.39434616992868204,
  -0.39430107535576897,
  -0.528254602108775,
  -0.5281085074623485,
  -0.5280705698054698,
  -0.5280129945338811,
  -0.6570605867948519,
  -0.6568902090927229,
  -0.6568469769004553,
  -0.6567764369943077,
  -0.30082224321461115,
  -0.022423449277664657,
  -0.097