In [6]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [7]:
dataset = pd.read_csv("C:/Users/88001381/Downloads/PV11 (1).csv")
print(dataset.shape)
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

(192936, 87)


In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30, random_state = 0)
print(X_train)
print(y_train)
print(X_test)
print(y_test)



[[94495 5003318165 202203 ... 0.461893764 19150.0 1.0]
 [148735 5003916669 202204 ... 0.780286797 10300.0 1.0]
 [116416 5003514659 202203 ... 0.747980214 15492.0 1.0]
 ...
 [117953 5003549253 202203 ... 0.786387841 13215.0 1.0]
 [173686 5004069565 202110 ... 0.484918669 843.0 1.0]
 [43568 5002839099 202110 ... 0.990132997 9438.0 1.0]]
[1. 1. 1. ... 1. 1. 1.]
[[138089 5003760975 202110 ... 0.898626993 9765.0 1.0]
 [166934 5004064055 202207 ... 0.474727627 724.0 1.0]
 [137080 5003748039 202111 ... 1.0 1027.0 1.0]
 ...
 [5014 5002360978 202203 ... 0.80912477 21900.0 1.0]
 [8130 5002434932 202109 ... 1.0 12355.0 1.0]
 [65588 5003030727 202110 ... 0.753068755 7827.0 1.0]]
[1. 1. 1. ... 1. 1. 1.]


In [9]:
dataset 

Unnamed: 0       CONNO   Month  FIN_AMOUNT        PRODUCT  NORM  \
0                1  5002011863  202109    474990.0        ZEST XM  SALG   
1                2  5002012526  202109    537283.0  INDIGO ECS LX  FTU2   
2                3  5002012526  202110    537283.0  INDIGO ECS LX  FTU2   
3                4  5002012738  202109    613000.0       ZEST XMS  SANG   
4                5  5002012738  202110    613000.0       ZEST XMS  SANG   
...            ...         ...     ...         ...            ...   ...   
192931      192932  8000178619  202208    288870.0        ZEST XE   STR   
192932      192933  8000178645  202208    276216.0        ZEST XE   STR   
192933      192934  8000178647  202208    289112.0        ZEST XE   STR   
192934      192935  8000178651  202208    288701.0        ZEST XE   STR   
192935      192936  8000179615  202208    527387.0   MM TOURISTER  SRT1   

        IRR_CUSTOMER                     APPLICATION_USAGE ASSET_CATEGORY2  \
0             12.467                              Personal             CAR   
1             15.547                                Others             CAR   
2             15.547                                Others             CAR   
3             12.097                              Personal             CAR   
4             12.097                              Personal             CAR   
...              ...                                   ...             ...   
192931        12.520  Bus Operation - Staff Transportation             CAR   
192932        12.539  Bus Operation - Staff Transportation             CAR   
192933        12.534  Bus Operation - Staff Transportation             CAR   
192934        12.518  Bus Operation - Staff Transportation             CAR   
192935        22.119                            School Bus         NON TML   

                 STATE  ... Tot_X_3M Bounce_1M  Last_2M_Cons_Del  \
0           TAMIL NADU  ...        0         0                 0   
1          WEST BENGAL  ...        0         0                 0   
2          WEST BENGAL  ...        0         0                 0   
3       ANDHRA PRADESH  ...        1         1                 0   
4       ANDHRA PRADESH  ...        2         1                 0   
...                ...  ...      ...       ...               ...   
192931       TELANGANA  ...        0         0               999   
192932       TELANGANA  ...        0         0               999   
192933       TELANGANA  ...        0         0               999   
192934       TELANGANA  ...        0         0               999   
192935      TAMIL NADU  ...        0         0               999   

        Last_3M_Cons_Del Last_6M_Cons_Del Del_in_Last_12M ASSET_LTV     EMI1  \
0                      0                0               0  0.702521  10800.0   
1                      0                0               1  0.853856  14658.0   
2                      0                0               1  0.853856  14658.0   
3                      0                0               4  0.848852  14600.0   
4                      0                0               3  0.848852  14600.0   
...                  ...              ...             ...       ...      ...   
192931               999              999               0  0.921435      NaN   
192932               999              999               0  0.923028      NaN   
192933               999              999               0  0.922207      NaN   
192934               999              999               0  0.920896      NaN   
192935               999              999               0  0.613241      NaN   

             ME1       CE1  
0       1.000000  1.000000  
1       1.000000  1.000000  
2       1.000000  1.000000  
3       3.811949  3.811949  
4       1.000000  1.000000  
...          ...       ...  
192931  1.000000  1.000000  
192932  1.000000  1.000000  
192933  1.000000  1.000000  
192934  1.000000  1.000000  
192935  1.000000  1.000000  

[192936 rows x 87 columns]

In [37]:
dataset["target_variable"] 

0         0
1         0
2         1
3         0
4         0
         ..
135050    0
135051    0
135052    0
135053    0
135054    0
Name: target_variable, Length: 135055, dtype: int64

In [30]:
from sklearn.model_selection import train_test_split
 
train_dataset, test_dataset = train_test_split(dataset, test_size=0.3)
 

In [35]:
train_dataset.to_excel('train.xlsx', index=False)
test_dataset.to_excel('test.xlsx', index=False)

In [11]:
train = pd.read_excel(r"C:/Users/88001381/Desktop/train.xlsx")


In [12]:
train.head()

Unnamed: 0       CONNO   Month  FIN_AMOUNT            PRODUCT  NORM  \
0       95275  5003340179  202112    700000.0  TATA ALTROZ XZ(O)  SENP   
1      157117  5004057467  202203    509126.0           TIAGO XT  SALG   
2      174528  5004070553  202207    120169.0           EWCL_CAR   FTU   
3      105415  5003414449  202112   1707863.0   HARRIER XZA PLUS  SENP   
4      151354  5003934734  202202    493011.0           TIAGO XT  SENP   

   IRR_CUSTOMER APPLICATION_USAGE ASSET_CATEGORY2       STATE  ... Tot_X_3M  \
0         9.981          Personal             CAR   KARNATAKA  ...        0   
1        11.359       Two Wheeler             CAR  NORTH EAST  ...        0   
2        13.968  Commercial- Taxi             CAR   TELANGANA  ...        0   
3         9.889          Personal             MUV     GUJARAT  ...        1   
4        11.525          Personal             CAR       BIHAR  ...        0   

  Bounce_1M  Last_2M_Cons_Del  Last_3M_Cons_Del Last_6M_Cons_Del  \
0         0                 0                 0                0   
1         0                 0                 0                0   
2         0                 0                 0                0   
3         0                 0                 0                0   
4         0                 0                 0                0   

  Del_in_Last_12M ASSET_LTV     EMI1  ME1  CE1  
0               0  0.750360  22580.0  1.0  1.0  
1               0  0.708274   8820.0  1.0  1.0  
2               0  0.888646   1402.0  1.0  1.0  
3               0  1.000000  81914.0  1.0  1.0  
4               0  0.752804  11000.0  1.0  1.0  

[5 rows x 87 columns]

In [32]:
dataset = train

In [14]:
dataset.columns.values.tolist()

['Unnamed: 0',
 'CONNO',
 'Month',
 'FIN_AMOUNT',
 'PRODUCT',
 'NORM',
 'IRR_CUSTOMER',
 'APPLICATION_USAGE',
 'ASSET_CATEGORY2',
 'STATE',
 'BRANCH_NEW',
 'REGION_NEW',
 'ASSET_COST',
 'LTV',
 'CUSTOMER_SEGMENT',
 'COMPANY_INDIVIDUAL',
 'DSA_DLR',
 'SOURCING',
 'PDC_FLAG',
 'SCHEME_FINPROD',
 'COMPANY_CODE',
 'COLLECTION_TILL_DATE',
 'SOHP',
 'TENURE',
 'ODAMT',
 'COLLECTION_MONTH',
 'FIRST_EMI',
 'EMI',
 'TRACK_RECORD',
 'ODBKT',
 'STATUS',
 'INCEPTION_MONTH',
 'MOB',
 'SOHPOD',
 'SOHPOD_PREASSIGN',
 'SOHPOD_MOB1PLUS',
 'SOHPOD_MOB2PLUS',
 'SOHPOD_MOB3PLUS',
 'SOHPOD_MOB4PLUS',
 'SOHPOD_MOB5PLUS',
 'SOHPOD_MOB6PLUS',
 'Restructuring_Flag',
 'SEGMENT',
 'PAID_PER',
 'TENURE_LEFT',
 'ME',
 'CE',
 'max_odbkt',
 'Ever_30',
 'Ever_60',
 'Ever_90',
 'DELSTRING_PAST24M',
 'DELSTRING_PAST24M_WOCOVID',
 'max_dpd',
 'target_variable',
 'XBktString_L24M',
 'EverInBkt_1_3M',
 'EverInBkt_2_3M',
 'EverInBkt_3_3M',
 'EverInBkt_4Plus_3M',
 'EverInBkt_1_6M',
 'EverInBkt_2_6M',
 'EverInBkt_3_6M',
 'Ev

In [15]:
from CHAID import Tree
import ast
from tqdm import tqdm
tqdm.pandas()
import re

In [16]:
binning_dict = dict()

In [17]:
import CHAID

In [184]:
independent_variable_columns = ['DELSTRING_PAST24M']
dep_variable = ["target_variable"]

tree = Tree.from_pandas_df(dataset, dict(zip(independent_variable_columns, ['nominal'] * 1)), 
                           dep_variable)
a = tree.tree_store[0]
a = ast.literal_eval(a.split.groupings)

def ApplicationUsage(x,a):
    y = ""
    for i,value in enumerate(a):
        if(x in value):
            y = i
    return(y)
    
dataset["DELSTRING_PAST24M_B"] = dataset["DELSTRING_PAST24M"].fillna('<missing>').apply(lambda x: ApplicationUsage(x,a))


KeyboardInterrupt: 

In [178]:
temp = dict()
for i,value in enumerate(a):
    temp[str(i)] = value
    
x = "DELSTRING_PAST24M_B"
for i in temp.keys():
    if(len(dataset[dataset[x].isin([int(i)])]["target_variable"].value_counts()) == 2):
        a1 = dataset[dataset[x].isin([int(i)])]["target_variable"].value_counts()[1]
        a2 = dataset[dataset[x].isin([int(i)])]["target_variable"].value_counts()[0]
        temp[i].append(["YES: " + str(a1) + " || NO: " + str(a2) + " || Bad%: " + str(round(a1/(a1+a2),4)*100)[0:5] + "%"])
    else:
        if(dataset[dataset[x].isin([int(i)])]["target_variable"].value_counts().index[0] == 0):
            a2 = dataset[dataset[x].isin([int(i)])]["target_variable"].value_counts()[0]
            temp[i].append(["YES: " + str(0) + " || NO: " + str(a2) + " || Bad%: " + str(round(a1/(a1+a2),4)*100)[0:5] + "%"])
        else:
            a1 = dataset[dataset[x].isin([int(i)])]["target_variable"].value_counts()[1]
            temp[i].append(["YES: " + str(a1) + " || NO: " + str(0) + " || Bad%: " + str(round(a1/(a1+a2),4)*100)[0:5] + "%"])
    
    
binning_dict["DELSTRING_PAST24M"] = temp 


In [179]:
dataset["ASSET_CATEGORY2_B"].value_counts()

0    133181
2      1058
1       816
Name: ASSET_CATEGORY2_B, dtype: int64

In [170]:
binning_dict

{'STATE': {'0': ['ANDHRA PRADESH',
   'JAMMU',
   ['YES: 525 || NO: 3191 || Bad%: 14.13%'],
   ['YES: 0 || NO: 43 || Bad%: 82.52%']],
  '1': ['BIHAR',
   ['YES: 153 || NO: 5602 || Bad%: 2.659%'],
   ['YES: 32 || NO: 229 || Bad%: 12.26%']],
  '2': ['CHHATTISGARH',
   'JHARKHAND',
   'TAMIL NADU',
   'ORISSA',
   ['YES: 2765 || NO: 19210 || Bad%: 12.58%'],
   ['YES: 24 || NO: 221 || Bad%: 9.8%']],
  '3': ['DELHI-NCR',
   'GUJARAT',
   'NORTH EAST',
   'HIMACHAL PRADESH',
   'UTTARANCHAL',
   'KARNATAKA',
   'MADHYA PRADESH',
   ['YES: 3187 || NO: 38186 || Bad%: 7.7%'],
   ['YES: 101 || NO: 381 || Bad%: 20.95%']],
  '4': ['HARYANA',
   'ROM',
   'TELANGANA',
   ['YES: 2038 || NO: 20413 || Bad%: 9.08%'],
   ['YES: 10 || NO: 56 || Bad%: 15.15%']],
  '5': ['KERALA',
   'PUNJAB',
   'RAJASTHAN',
   'WEST BENGAL',
   'UTTAR PRADESH 1',
   'UTTAR PRADESH 2',
   'VIDARBH',
   ['YES: 3688 || NO: 32455 || Bad%: 10.2%'],
   ['YES: 0 || NO: 37 || Bad%: 21.27%']],
  '6': ['MUMBAI',
   ['YES: 203 || N

In [180]:
binning1 = pd.DataFrame(columns = ["Group","Binning","YES","NO"])
for j in binning_dict.keys():
    x = []
    for i in binning_dict[j].keys():
        try: 
            temp1 = binning_dict[j][i]
            temp = [i,''.join(str(temp1[:len(temp1)-1])),re.findall(r'\d+',temp1[-1][0])[0],re.findall(r'\d+',temp1[-1][0])[1]]
            x.append(temp)
        except:
            temp = [str(i),','.join(temp1[:len(temp1)-1]),"0","1"]
            x.append(temp)
    temp2 = pd.DataFrame(x,columns = ["Group","Binning","YES","NO"])
    temp2["Variable"] = [j for i in range(len(binning_dict[j].keys()))]
    temp2["Bad%"] = temp2["YES"].astype("int")/(temp2["NO"].astype("int")+temp2["YES"].astype("int"))
    binning1 =pd.concat([binning1,temp2],axis =0)
binning1.insert(0, "Variables", binning1["Variable"])
binning1 = binning1.drop(["Variable"],axis =1)


In [181]:
binning1

Variables Group  \
0                STATE     0   
1                STATE     1   
2                STATE     2   
3                STATE     3   
4                STATE     4   
..                 ...   ...   
3         TRACK_RECORD     3   
0   Restructuring_Flag     0   
1   Restructuring_Flag     1   
2   Restructuring_Flag     2   
3   Restructuring_Flag     3   

                                              Binning    YES     NO      Bad%  
0   ['ANDHRA PRADESH', 'JAMMU', ['YES: 525 || NO: ...      0     43  0.000000  
1   ['BIHAR', ['YES: 153 || NO: 5602 || Bad%: 2.65...     32    229  0.122605  
2   ['CHHATTISGARH', 'JHARKHAND', 'TAMIL NADU', 'O...     24    221  0.097959  
3   ['DELHI-NCR', 'GUJARAT', 'NORTH EAST', 'HIMACH...    101    381  0.209544  
4   ['HARYANA', 'ROM', 'TELANGANA', ['YES: 2038 ||...     10     56  0.151515  
..                                                ...    ...    ...       ...  
3                                             ['PTR']   4306   9541  0.310970  
0                                            ['EWCL']    719  18781  0.036872  
1                                        ['Fastrack']   1150   7502  0.132917  
2                                            ['MSME']    279    528  0.345725  
3                                          ['Normal']  10411  95685  0.098128  

[4694 rows x 6 columns]

In [182]:
binning1.to_excel('binning2.xlsx', index=False)

In [183]:
dataset.to_csv('PV_WITHOUT_BUSES_Model_Data.csv', index=False)